# permissions for end users to edit tunnelingresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: tunnelingress-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cloudflared-operator
    app.kubernetes.io/part-of: cloudflared-operator
    app.kubernetes.io/managed-by: kustomize
  name: tunnelingress-editor-role
rules:
- apiGroups:
  - cloudflared-operator.bhyoo.com
  resources:
  - tunnelingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudflared-operator.bhyoo.com
  resources:
  - tunnelingresses/status
  verbs:
  - get
